### PR TITLE
Migration changes from community.yang  to supported ansible.yang collection

### PR DESCRIPTION
**Pull request by rohitthakur2590**
Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by trishnaguha** [comment]
@rohitthakur2590 Python3.9 unit and integration tests need to be added for yang to be released as supported.

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Review by KB-perByte — APPROVED** [review]

**Comment by trishnaguha** [comment]
@rohitthakur2590 For all collections netcommon minimum version is being set to 2.5.1 in galaxy.yml. Is that necessary for the YANG collection?

**Comment by rohitthakur2590** [comment]
> @rohitthakur2590 For all collections netcommon minimum version is being set to 2.5.1 in galaxy.yml. Is that necessary for the YANG collection?

Hey thanks for pointing it out, It should be good with >= 2.5.1 and same have been updated

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Pull request merged**
